### ISSUE TITLE
warp ctc error

### ISSUE THREAD

**Issue by shubham-IISc** [jinserk/pytorch-asr#1]
![screenshot from 2018-07-30 22-54-24](https://user-images.githubusercontent.com/35381101/43443876-d0266d44-94bf-11e8-8e5a-cd96738e06fc.png)
Hey. I am getting this issue while running setup.py install. Can you please help me with this.
I am using pytorch 0.4 , cuda 8 and anaconda2.

Thanks

**Comment by jinserk** [comment]
You'd better to ask this to [warp-ctc](https://github.com/SeanNaren/warp-ctc) project. Sorry for too late reply but this project doesn't provide any setup.py at all.
